# If the branch has been deleted - clean cf

on: [delete]
  #  release:
#types: [created]

name: Clean CF

env:
  TYPE: ${{ github.event.ref_type }}

jobs:
  clean-cf:
    name: Prepare CF for testing. Cleanup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      
      - name: Cleanup ENV for current branch
        uses: ./.github/actions/clean-failed
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_user: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
